### ISSUE TITLE
Add to gradle plugins repo

### ISSUE THREAD

**Issue by jaredsburrows** [evant/android-retrolambda-lombok#15]
Can you add this to the gradle plugins repo similar to your https://github.com/evant/gradle-retrolambda plugin?

**Comment by JakeWharton** [comment]
This isn't a Gradle plugin though. It's just a jar which can be used as a replacement for the normal lombok dependency.

**Comment by jaredsburrows** [comment]
@JakeWharton Then how can I add this to my `classpath` via the new `plugins` block? I am in the middle of converting my existing repos that use the older `buildscript`.

```
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }                      // Mirrors jcenter() and mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:2.1.2"                    // Android gradle plugin
        classpath "com.novoda:gradle-android-command-plugin:1.5.0"          // Android command plugin
        classpath "com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.5.4"   // Dex method count
        classpath "com.vanniktech:gradle-android-apk-size-plugin:0.2.0"     // Apk size
        classpath "me.tatarka:gradle-retrolambda:3.2.5"                     // Java 8 lambda support
        classpath "me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2"
        classpath "com.neenbedankt.gradle.plugins:android-apt:1.8"          // Annotation processing
    }
}

plugins {
    id "com.gradle.build-scan" version "1.0"                                // Gradle build receipt
    id "net.ltgt.errorprone" version "0.0.8"                                // Google error-prone
    id "com.github.kt3k.coveralls" version "2.6.3"                          // Code coverage
    id "com.github.ben-manes.versions" version "0.12.0"                     // Check for plugin updates
    id "build-dashboard"
    id "jacoco"
}

repositories {
    maven { url "https://plugins.gradle.org/m2/" }                          // Mirrors jcenter() and mavenCentral()
    maven { url "https://jitpack.io" }
}
```

I am thinking there is no point in moving to the new `plugins` block if I can't move everything out of the `buildscript` block.

**Comment by JakeWharton** [comment]
> Then how can I add this to my `classpath` via the new `plugins` block?

You cannot.

> I am thinking there is no point in moving to the new `plugins` block if I can't move everything out of the `buildscript` block.

Hmm I'm not sure I agree. You can move all your actual plugins to `plugins` but keep `buildscript` for modifying the classpath of the build itself which is what this library is for.

**Comment by jaredsburrows** [comment]
@JakeWharton Thanks. I guess it could be clear to decouple plugins from buildscript dependencies by separating `buildscript`, `plugins` and `repositories`.
