### ISSUE TITLE
Retrolambda plugin 3.3.0 doesn't strip calls to addSuppressed when using try-with-resources

### ISSUE THREAD

**Issue by thevery** [evant/android-retrolambda-lombok#18]
lint produces a warning about this issue (and I've checked generated files as well - 3.2.5 ok, 3.3.0 broken)

```
classpath 'com.android.tools.build:gradle:2.2.0'
classpath 'me.tatarka:gradle-retrolambda:3.3.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

minSdkVersion 15
```

**Comment by thevery** [comment]
`classpath 'com.android.tools.build:gradle:2.1.3'` doesn't work, too

**Comment by JakeWharton** [comment]
This is not the right project for that issue. You want https://github.com/evant/gradle-retrolambda

**Comment by thevery** [comment]
@JakeWharton I've checked 3.2.5 + retrolabda 2.3.0 and it is still broken, so something definitely changed in plugin itself (maybe some compatibility not passed properly?).

**Comment by thevery** [comment]
@JakeWharton ic, my bad. Thanks!

**Comment by thevery** [comment]
https://github.com/evant/gradle-retrolambda/issues/208
