### ISSUE TITLE
Test LiveServiceManager once dagger 2 can replace modules in test code

### ISSUE THREAD

**Issue by paul-turner** [evant/android-retrolambda-lombok#6]
See issues:
https://bitbucket.org/hvisser/android-apt/issue/22/dagger-robolectric-gradle-apt-source-not
and 
https://code.google.com/p/android/issues/detail?id=154651

**Comment by evant** [comment]
Not sure what this has to do with lint, are you sure you didn't mean to put this on https://github.com/evant/gradle-retrolambda? Can you also explain exactly what the issue is? gradle-retrolmaba should already support unit tests.

**Comment by paul-turner** [comment]
sorry :( opened the wrong repo, this was an issue for myself :-1:
