### ISSUE TITLE
Android Lint claims NewApi for try-with-resources

### ISSUE THREAD

**Issue by ypresto** [evant/android-retrolambda-lombok#9]
With retrolambda and android lint, I got "Try-with-resources requires API level 19 (current min is 14)" on below line.

```
try (Realm realm = getRealm()) {
```

But to suppress this requires ignoring all NewApi usage incl. other than try-with-resources.
Is there any workaround for this..?

**Comment by adelnizamutdinov** [comment]
unfortunately try-with-resources is available only with minSdkLevel 19 and has nothing to do to retrolambda
http://stackoverflow.com/a/24290875/1032286

**Comment by ypresto** [comment]
Really? README of retrolambada says it runs on Java 6.

> Retrolambda lets you run Java 8 code with lambda expressions, method references and try-with-resources statements on Java 7, 6 or 5.

**Comment by adelnizamutdinov** [comment]
@ypresto I'm sorry, I might be wrong

regarding Lint I don't really know what can you do here

**Comment by evant** [comment]
Yes retrolamda will backport try-with-resources. Unfortunately, I don't think there is a way to disable only part of a lint check. Lint itself could be forked, but I didn't want to do that since it would be a burdan to maintain. Other than the options above, you could also annotate your try-with-resources usages to be ignored.

**Comment by evant** [comment]
```xml
  <issue id="NewApi">
    <ignore regexp="Try-with-resources requires API level 19"/>
  </issue>
```

**Comment by evant** [comment]
Added info to suppress lint check to README, closing.

**Comment by ypresto** [comment]
thanks!

**Comment by ypresto** [comment]
oops.. Android Studio also claims it. But there seems to be no regexp option.
